### ISSUE TITLE
Development Plan Revision 0 Brainstorm Area

### ISSUE THREAD

**Issue by qinj15** [wangq131/4G06CapstoneProjectT5#2]
- [x] Team Meeting Plan
- [x] Team Communication Plan
- [x] Team Member Roles
- [x] Workflow Plan

**Comment by katrina799** [comment]
Brainstorm ideas:
- [x] A branch protection rule is created for main branch, code changes cannot be merged to the main branch directly, it can only be done by creating a PR, and at least two team members need to review and approve the PR before it can be merged
- [x] Each push should be checked by the `main.yml` workflow. The `main.yml` will perform linter check, testing, etc, to make sure code changes is aligned with our code standards and will not break anything
- [x] Each PR body should follow the format of the PR template created
- [x] Every PR should have at least one label associated with it, and should have an issue linked to it, otherwise, the PR check workflow will fail and the PR cannot be merged 
- [x] A draft PR should be created when it is still under development,  a regular PR should be opened only when it is ready for a review
- [x] When creating a generic issue, the issue body should follow the template provided for the generic issue
- [x] When creating an issue for meeting documentation, the issue body should follow the template provided for recording meeting information
- [x] An issue should have at least one labels, and at least one assignees, and project linked to it 
- [x] An issue should be put under `Todo` inside the project board when it gets created
- [x] An issue should be put under `In Progress` inside the project board when someone picks it up and starts working on it
- [x] An issue should be put under `In Verification` when it is ready for a review or a verification 
- [x] An issue should be put under `Done` once it gets completed
- [x] A dev container should be used for development to ensure everyone is developing under the same configurations/environment
- [x] A feature branch should be created under development
- [x] A person will be responsible for managing our project board and issues to ensure issues are being put under the correct section, and to make sure issues are assigned and set up weekly meetings to go over the progress of each issue.
